name: Website CI (test.datacore.app)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      env:
        GATSBY_DATACORE_URL: https://test.datacore.app
        GATSBY_ASSETS_URL: https://assets.datacore.app
      run: |
        npm install
        npm run build
    - name: Publish to server via sftp
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.SFTP_HOST }}
        ftp-username: ${{ secrets.SFTP_USER }}
        ftp-password: ${{ secrets.SFTP_PASS }}
        known-hosts: ${{ secrets.SFTP_KNOWNHOSTS }}
        local-dir: ./public
